### ISSUE TITLE
Including `sequel-honeycomb` seems to trigger `uninitialized constant Sequel::Model (NameError)` 

### ISSUE THREAD

**Issue by christineyen** [honeycombio/sequel-honeycomb#2]
This happens when trying to include the `honeycomb-beeline` gem into https://github.com/thepracticaldev/dev.to =\

```
17:18:22 web.1       | => Rails 5.1.6 application starting in development
17:18:22 web.1       | => Run `rails server -h` for more startup options
17:18:22 web.1       | Exiting
17:18:22 web.1       | **Airbrake: closed
17:18:22 web.1       | /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/algoliasearch-rails-1.20.4/lib/algoliasearch-rails.rb:401:in `algoliasearch': uninitialized constant Sequel::Model (NameError)
17:18:22 web.1       | 	from /Users/cyen/src/honeycomb/oss/dev.to/app/models/article.rb:95:in `<class:Article>'
17:18:22 web.1       | 	from /Users/cyen/src/honeycomb/oss/dev.to/app/models/article.rb:1:in `<top (required)>'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/concurrency/share_lock.rb:149:in `exclusive'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/dependencies/interlock.rb:11:in `loading'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:269:in `const_get'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:269:in `block in constantize'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:267:in `each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:267:in `inject'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/inflector/methods.rb:267:in `constantize'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/object/try.rb:17:in `public_send'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/object/try.rb:17:in `try!'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/core_ext/object/try.rb:6:in `try'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:334:in `observed_class'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:325:in `observed_classes'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:345:in `observed_classes'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/activerecord/observer.rb:100:in `observed_classes'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:341:in `initialize'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/singleton.rb:141:in `new'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/singleton.rb:141:in `block in instance'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/singleton.rb:139:in `synchronize'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/singleton.rb:139:in `instance'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:186:in `instantiate_observer'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:108:in `block in instantiate_observers'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:108:in `each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/active_model/observing.rb:108:in `instantiate_observers'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/railtie.rb:42:in `block (2 levels) in <class:Railtie>'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:41:in `block in on_load'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:40:in `each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:40:in `on_load'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rails-observers-0.1.5/lib/rails/observers/railtie.rb:41:in `block in <class:Railtie>'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:67:in `block in execute_hook'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/application/finisher.rb:73:in `block in <module:Finisher>'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `instance_exec'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:30:in `run'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:59:in `block in run_initializers'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `call'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/initializable.rb:58:in `run_initializers'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.1.6/lib/rails/application.rb:353:in `initialize!'
17:18:22 web.1       | 	from /Users/cyen/src/honeycomb/oss/dev.to/config/environment.rb:5:in `<top (required)>'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/skylight-core-2.0.2/lib/skylight/core/probes.rb:119:in `require'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/skylight-core-2.0.2/lib/skylight/core/probes.rb:119:in `require'
17:18:22 web.1       | 	from config.ru:6:in `block in <main>'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
17:18:22 web.1       | 	from config.ru:in `new'
17:18:22 web.1       | 	from config.ru:in `<main>'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
17:18:22 web.1       | 	from /Users/cyen/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
```

**Comment by martin308** [comment]
This was fixed by #3 🎉
